### ISSUE TITLE
Design Project scope

### ISSUE THREAD

**Issue by drewlearns** [drewlearns/OS_100days#1]
Brainstorm session needs scheduled on discord to discuss what the project will entail. Design a scope document out of it and a contributions document.

**Comment by renners7777** [comment]
Purpose: Reminder function for anyone completing 100DaysofCode.

Target audience? Anyone completing 100DaysofCode plus anyone who might be interested in doing it. Establishing links with current 100DaysofCode community? Would we seek support from https://www.100daysofcode.com/ authors?

Website design & functionality? Who is going to do what? Accessibility?

Research - is anything similar already available? I know that there are bots, etc, which automatically retweet @100DaysofCode tweets.  I am sure Drew has already considered this!

These are just some initial thoughts. Look forward to meeting you tonight.
