### ISSUE TITLE
Logo design ideas?

### ISSUE THREAD

**Issue by renners7777** [drewlearns/OS_100days#17]
Hi all,

Have a think about the "name" + "logo" for our app. I'll kick us off: 
https://user-images.githubusercontent.com/104800006/195441882-1d80d1b7-1b44-496d-a579-8c2c17a91f31.png
(url)
Created using FreeLogoDesign

**Comment by renners7777** [comment]
I am not a designer so am sure someone else out there can do better

**Comment by mathcodes** [comment]
I'm game for throwing down some ideas!

**Comment by renners7777** [comment]
Go for it.

**Comment by mathcodes** [comment]
Working on logo designs... but I'll also list some ideas for names here as well... prepare for some cheesiness and don't hesitate to reject on the spot, lol.

"100 Days of Cues" then a slogan like... "daily reminders to keep you coding"
"100 Chimes to Code"

LOGOS otw

**Comment by lavish-lekhari** [comment]
I can do the logo thingy.

**Comment by renners7777** [comment]
We have chosen the logo now. Thank you all for your contributions.
