### ISSUE TITLE
Create Structure

### ISSUE THREAD

**Issue by D-KILLJOY** [drewlearns/OS_100days#3]
We'll start by creating the basic HTML structure for the project.
![IMG_20221010_085814.jpg](https://user-images.githubusercontent.com/106471559/195103579-3fe4e420-c700-4912-ab2d-7186fef44824.jpg)

**Comment by rahmancodes** [comment]
I would love to also contribute to the HTML structure for this project.

**Comment by D-KILLJOY** [comment]
> Killjoy - can you share the templates you put on Discord here please?

I've added it 
I just edited the issue and added it
