### ISSUE TITLE
faq goes to the wrong page/section. 

### ISSUE THREAD

**Issue by drewlearns** [drewlearns/OS_100days#38]
faq section needs an id of #faq and then the link needs to be updated in the partials/navbar.ejs to /about/#faq

**Comment by VaibhaV-R-N** [comment]
assign  me this.

**Comment by drewlearns** [comment]
![7 5 md — Dev-Local 2022-10-24 at 17 22 41](https://user-images.githubusercontent.com/54754951/197632123-553e004a-74ab-44bd-a068-aac9a048a402.jpg)
