### ISSUE TITLE
index.js titles should have our domain name in them 

### ISSUE THREAD

**Issue by drewlearns** [drewlearns/OS_100days#40]
currently it just says "about" or "faq" but it probably would be best to set a variable called domain and call it from the index.js for the specific routes. ie. " example.com | about"
![New Issue · drewlearnsOS_100days 2022-10-24 at 08 12 59](https://user-images.githubusercontent.com/54754951/197522836-8f9031d7-ff62-4f45-b048-5e36038dc1b4.jpg)

**Comment by Arcturus22** [comment]
@drewlearns 
I am not able to understand it completely.
Can you please elaborate a bit more on this issue?

**Comment by VaibhaV-R-N** [comment]
assign me please.
